-- Generated by scripts/gen-theme.py from
-- comms/shared/theming/lex-theme.json. Do not edit by hand.
--
-- Lex Monochrome palette + token rules consumed by
-- lua/lex/theme.lua's apply_monochrome path.

local M = {}

M.COLORS = {
  dark = {
    normal = "#e0e0e0",
    muted = "#888888",
    faint = "#666666",
    faintest = "#555555",
    code_bg = "#2a2a2a",
  },
  light = {
    normal = "#000000",
    muted = "#808080",
    faint = "#b3b3b3",
    faintest = "#cacaca",
    code_bg = "#f5f5f5",
  },
}

-- Each entry: { token, intensity, bold?, italic?, underline?, background? }
-- intensity ∈ { 'normal', 'muted', 'faint', 'faintest' }; background
-- references a key in COLORS[mode] (currently only 'code_bg').
M.TOKENS = {
  { token = "DocumentTitle", intensity = "normal", bold = true, underline = true },
  { token = "DocumentSubtitle", intensity = "normal", italic = true },
  { token = "SessionTitleText", intensity = "normal", bold = true },
  { token = "SessionMarker", intensity = "muted", italic = true },
  { token = "DefinitionSubject", intensity = "normal", italic = true },
  { token = "DefinitionContent", intensity = "normal" },
  { token = "ListMarker", intensity = "muted", italic = true },
  { token = "ListItemText", intensity = "normal" },
  { token = "InlineStrong", intensity = "normal", bold = true },
  { token = "InlineEmphasis", intensity = "normal", italic = true },
  { token = "InlineCode", intensity = "normal" },
  { token = "InlineMath", intensity = "normal", italic = true },
  { token = "Reference", intensity = "muted", underline = true },
  { token = "ReferenceCitation", intensity = "muted", underline = true },
  { token = "ReferenceFootnote", intensity = "muted", underline = true },
  { token = "ReferenceAnnotation", intensity = "muted", underline = true },
  { token = "AnnotationLabel", intensity = "faint" },
  { token = "AnnotationParameter", intensity = "faint" },
  { token = "AnnotationContent", intensity = "faint" },
  { token = "VerbatimSubject", intensity = "faint" },
  { token = "VerbatimLanguage", intensity = "faint" },
  { token = "VerbatimAttribute", intensity = "faint" },
  { token = "VerbatimContent", intensity = "normal", background = "code_bg" },
  { token = "InlineMarker_strong_start", intensity = "faintest", italic = true },
  { token = "InlineMarker_strong_end", intensity = "faintest", italic = true },
  { token = "InlineMarker_emphasis_start", intensity = "faintest", italic = true },
  { token = "InlineMarker_emphasis_end", intensity = "faintest", italic = true },
  { token = "InlineMarker_code_start", intensity = "faintest", italic = true },
  { token = "InlineMarker_code_end", intensity = "faintest", italic = true },
  { token = "InlineMarker_math_start", intensity = "faintest", italic = true },
  { token = "InlineMarker_math_end", intensity = "faintest", italic = true },
  { token = "InlineMarker_ref_start", intensity = "faintest", italic = true },
  { token = "InlineMarker_ref_end", intensity = "faintest", italic = true },
}

return M
