-- Generated by scripts/gen-theme.py from
-- comms/shared/theming/lex-theme.json. Do not edit by hand.
--
-- Lex Monochrome highlight rules, pre-resolved per mode. Consumed
-- by lua/lex/theme.lua's apply_monochrome path.

local M = {}

-- Per-mode intensity palette. Exposed for the user-overridable
-- @lex.{normal,muted,faint,faintest} base groups.
M.PALETTE = {
  dark = {
    normal = "#e0e0e0",
    muted = "#888888",
    faint = "#666666",
    faintest = "#555555",
  },
  light = {
    normal = "#000000",
    muted = "#808080",
    faint = "#b3b3b3",
    faintest = "#cacaca",
  },
}

-- Each entry: { token = ..., fg = ..., bold? = true,
--   italic? = true, underline? = true, bg? = ... }
-- All colors are absolute hex strings, resolved from canonical
-- intensity/background tiers at generate time.
M.RULES = {
  dark = {
    { token = "DocumentTitle", fg = "#e0e0e0", bold = true, underline = true },
    { token = "DocumentSubtitle", fg = "#e0e0e0", italic = true },
    { token = "SessionTitleText", fg = "#e0e0e0", bold = true },
    { token = "SessionMarker", fg = "#888888", italic = true },
    { token = "DefinitionSubject", fg = "#e0e0e0", italic = true },
    { token = "DefinitionContent", fg = "#e0e0e0" },
    { token = "ListMarker", fg = "#888888", italic = true },
    { token = "ListItemText", fg = "#e0e0e0" },
    { token = "InlineStrong", fg = "#e0e0e0", bold = true },
    { token = "InlineEmphasis", fg = "#e0e0e0", italic = true },
    { token = "InlineCode", fg = "#e0e0e0" },
    { token = "InlineMath", fg = "#e0e0e0", italic = true },
    { token = "Reference", fg = "#888888", underline = true },
    { token = "ReferenceCitation", fg = "#888888", underline = true },
    { token = "ReferenceFootnote", fg = "#888888", underline = true },
    { token = "ReferenceAnnotation", fg = "#888888", underline = true },
    { token = "AnnotationLabel", fg = "#666666" },
    { token = "AnnotationParameter", fg = "#666666" },
    { token = "AnnotationContent", fg = "#666666" },
    { token = "VerbatimSubject", fg = "#666666" },
    { token = "VerbatimLanguage", fg = "#666666" },
    { token = "VerbatimAttribute", fg = "#666666" },
    { token = "VerbatimContent", fg = "#e0e0e0", bg = "#2a2a2a" },
    { token = "InlineMarker_strong_start", fg = "#555555", italic = true },
    { token = "InlineMarker_strong_end", fg = "#555555", italic = true },
    { token = "InlineMarker_emphasis_start", fg = "#555555", italic = true },
    { token = "InlineMarker_emphasis_end", fg = "#555555", italic = true },
    { token = "InlineMarker_code_start", fg = "#555555", italic = true },
    { token = "InlineMarker_code_end", fg = "#555555", italic = true },
    { token = "InlineMarker_math_start", fg = "#555555", italic = true },
    { token = "InlineMarker_math_end", fg = "#555555", italic = true },
    { token = "InlineMarker_ref_start", fg = "#555555", italic = true },
    { token = "InlineMarker_ref_end", fg = "#555555", italic = true },
  },
  light = {
    { token = "DocumentTitle", fg = "#000000", bold = true, underline = true },
    { token = "DocumentSubtitle", fg = "#000000", italic = true },
    { token = "SessionTitleText", fg = "#000000", bold = true },
    { token = "SessionMarker", fg = "#808080", italic = true },
    { token = "DefinitionSubject", fg = "#000000", italic = true },
    { token = "DefinitionContent", fg = "#000000" },
    { token = "ListMarker", fg = "#808080", italic = true },
    { token = "ListItemText", fg = "#000000" },
    { token = "InlineStrong", fg = "#000000", bold = true },
    { token = "InlineEmphasis", fg = "#000000", italic = true },
    { token = "InlineCode", fg = "#000000" },
    { token = "InlineMath", fg = "#000000", italic = true },
    { token = "Reference", fg = "#808080", underline = true },
    { token = "ReferenceCitation", fg = "#808080", underline = true },
    { token = "ReferenceFootnote", fg = "#808080", underline = true },
    { token = "ReferenceAnnotation", fg = "#808080", underline = true },
    { token = "AnnotationLabel", fg = "#b3b3b3" },
    { token = "AnnotationParameter", fg = "#b3b3b3" },
    { token = "AnnotationContent", fg = "#b3b3b3" },
    { token = "VerbatimSubject", fg = "#b3b3b3" },
    { token = "VerbatimLanguage", fg = "#b3b3b3" },
    { token = "VerbatimAttribute", fg = "#b3b3b3" },
    { token = "VerbatimContent", fg = "#000000", bg = "#f5f5f5" },
    { token = "InlineMarker_strong_start", fg = "#cacaca", italic = true },
    { token = "InlineMarker_strong_end", fg = "#cacaca", italic = true },
    { token = "InlineMarker_emphasis_start", fg = "#cacaca", italic = true },
    { token = "InlineMarker_emphasis_end", fg = "#cacaca", italic = true },
    { token = "InlineMarker_code_start", fg = "#cacaca", italic = true },
    { token = "InlineMarker_code_end", fg = "#cacaca", italic = true },
    { token = "InlineMarker_math_start", fg = "#cacaca", italic = true },
    { token = "InlineMarker_math_end", fg = "#cacaca", italic = true },
    { token = "InlineMarker_ref_start", fg = "#cacaca", italic = true },
    { token = "InlineMarker_ref_end", fg = "#cacaca", italic = true },
  },
}

return M
