#!/usr/bin/env python3
"""Generate lua/lex/theme_data.lua from the canonical theme data in
`comms/shared/theming/lex-theme.json`.

Emits two per-mode tables of pre-resolved hex values:

  M.PALETTE = {
    dark  = { normal = "#...", muted = "#...", faint = "#...", faintest = "#..." },
    light = { ... },
  }

  M.RULES = {
    dark  = { { token = "...", fg = "#...", bold = true, ... }, ... },
    light = { { token = "...", fg = "#...", bold = true, ... }, ... },
  }

`M.PALETTE` exposes the four intensity tiers for the user-overridable
`@lex.{normal,muted,faint,faintest}` base groups. `M.RULES` is the
per-token highlight list; each entry's `fg` (and optional `bg`) is the
absolute hex value resolved from the canonical intensity/background tier
at generate time. The runtime in `lua/lex/theme.lua`'s
`apply_monochrome` picks both tables by `vim.o.background` and applies
entries directly to `nvim_set_hl` — no further indirection.

The `apply_native` and `apply_treesitter_*` paths stay hand-written:
they target tree-sitter captures and standard markup groups, not the
LSP semantic tokens encoded here.

Run after editing the canonical file. The pre-commit hook (and CI)
runs `gen-theme.py --check` to fail on stale output.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
CANONICAL = REPO_DIR / "comms" / "shared" / "theming" / "lex-theme.json"
TARGET = REPO_DIR / "lua" / "lex" / "theme_data.lua"


def lua_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_rules(canonical: dict, mode: str) -> str:
    intensities = canonical["intensities"]
    backgrounds = canonical.get("backgrounds", {})
    tokens = canonical["tokens"]

    lines = []
    for token_id, token in tokens.items():
        fields = [
            f"token = {lua_str(token_id)}",
            f"fg = {lua_str(intensities[token['intensity']][mode])}",
        ]
        styles = token.get("styles", [])
        for style in ("bold", "italic", "underline"):
            if style in styles:
                fields.append(f"{style} = true")
        if "background" in token:
            fields.append(f"bg = {lua_str(backgrounds[token['background']][mode])}")
        lines.append("    { " + ", ".join(fields) + " },")
    return "\n".join(lines)


def render_palette(canonical: dict, mode: str) -> str:
    intensities = canonical["intensities"]
    lines = [
        f"    {name} = {lua_str(intensities[name][mode])},"
        for name in ("normal", "muted", "faint", "faintest")
    ]
    return "\n".join(lines)


def render(canonical: dict) -> str:
    return (
        "-- Generated by scripts/gen-theme.py from\n"
        "-- comms/shared/theming/lex-theme.json. Do not edit by hand.\n"
        "--\n"
        "-- Lex Monochrome highlight rules, pre-resolved per mode. Consumed\n"
        "-- by lua/lex/theme.lua's apply_monochrome path.\n"
        "\n"
        "local M = {}\n"
        "\n"
        "-- Per-mode intensity palette. Exposed for the user-overridable\n"
        "-- @lex.{normal,muted,faint,faintest} base groups.\n"
        "M.PALETTE = {\n"
        "  dark = {\n"
        f"{render_palette(canonical, 'dark')}\n"
        "  },\n"
        "  light = {\n"
        f"{render_palette(canonical, 'light')}\n"
        "  },\n"
        "}\n"
        "\n"
        "-- Each entry: { token = ..., fg = ..., bold? = true,\n"
        "--   italic? = true, underline? = true, bg? = ... }\n"
        "-- All colors are absolute hex strings, resolved from canonical\n"
        "-- intensity/background tiers at generate time.\n"
        "M.RULES = {\n"
        "  dark = {\n"
        f"{render_rules(canonical, 'dark')}\n"
        "  },\n"
        "  light = {\n"
        f"{render_rules(canonical, 'light')}\n"
        "  },\n"
        "}\n"
        "\n"
        "return M\n"
    )


def main() -> int:
    if not CANONICAL.exists():
        print(
            f"FAIL: canonical theme not found at {CANONICAL.relative_to(REPO_DIR)}.\n"
            f"      Did you forget `git submodule update --init`?",
            file=sys.stderr,
        )
        return 1

    canonical = json.loads(CANONICAL.read_text(encoding="utf-8"))
    expected = render(canonical)
    TARGET.parent.mkdir(parents=True, exist_ok=True)

    if "--check" in sys.argv:
        if not TARGET.exists():
            print(f"FAIL: {TARGET.relative_to(REPO_DIR)} missing", file=sys.stderr)
            return 1
        # Read with explicit UTF-8 + normalize CRLF → LF before compare so
        # the check doesn't false-positive on Windows checkouts that
        # rewrite line endings.
        actual = TARGET.read_text(encoding="utf-8").replace("\r\n", "\n")
        expected_normalized = expected.replace("\r\n", "\n")
        if actual != expected_normalized:
            print(
                f"FAIL: {TARGET.relative_to(REPO_DIR)} out of sync.\n"
                f"      Run: python scripts/gen-theme.py",
                file=sys.stderr,
            )
            return 1
        print(f"  ✓ {TARGET.relative_to(REPO_DIR)} matches generator")
        return 0

    TARGET.write_text(expected, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
