#!/usr/bin/env python3
"""Generate lua/lex/theme-data.lua from the canonical theme data in
`comms/shared/theming/lex-theme.json`.

Emits two tables:

- M.COLORS — { dark = {...}, light = {...} } palettes covering the 4
  intensity tiers and the code_bg background.
- M.TOKENS — the token list, each entry { token, intensity, bold?,
  italic?, underline?, background? }. The `bold/italic/underline`
  booleans match what `vim.api.nvim_set_hl` accepts directly.

The runtime in `lua/lex/theme.lua` consumes these tables in its
`apply_monochrome` path. The `apply_native` path and the
`apply_treesitter_*` variants stay hand-written: they target a
different taxonomy (tree-sitter captures and standard markup groups),
not the LSP semantic tokens encoded here.

Run after editing the canonical file. The pre-commit hook (and CI)
runs `gen-theme.py --check` to fail on stale output.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
CANONICAL = REPO_DIR / "comms" / "shared" / "theming" / "lex-theme.json"
TARGET = REPO_DIR / "lua" / "lex" / "theme-data.lua"


def lua_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(canonical: dict) -> str:
    intensities = canonical["intensities"]
    backgrounds = canonical.get("backgrounds", {})
    tokens = canonical["tokens"]

    def palette_block(mode: str) -> str:
        lines = []
        for name in ("normal", "muted", "faint", "faintest"):
            lines.append(f"    {name} = {lua_str(intensities[name][mode])},")
        for bg_name, bg_values in backgrounds.items():
            lines.append(f"    {bg_name} = {lua_str(bg_values[mode])},")
        return "\n".join(lines)

    token_lines = []
    for token_id, token in tokens.items():
        fields = [f"token = {lua_str(token_id)}", f"intensity = {lua_str(token['intensity'])}"]
        styles = token.get("styles", [])
        for style in ("bold", "italic", "underline"):
            if style in styles:
                fields.append(f"{style} = true")
        if "background" in token:
            fields.append(f"background = {lua_str(token['background'])}")
        token_lines.append("  { " + ", ".join(fields) + " },")

    return (
        "-- Generated by scripts/gen-theme.py from\n"
        "-- comms/shared/theming/lex-theme.json. Do not edit by hand.\n"
        "--\n"
        "-- Lex Monochrome palette + token rules consumed by\n"
        "-- lua/lex/theme.lua's apply_monochrome path.\n"
        "\n"
        "local M = {}\n"
        "\n"
        "M.COLORS = {\n"
        "  dark = {\n"
        f"{palette_block('dark')}\n"
        "  },\n"
        "  light = {\n"
        f"{palette_block('light')}\n"
        "  },\n"
        "}\n"
        "\n"
        "-- Each entry: { token, intensity, bold?, italic?, underline?, background? }\n"
        "-- intensity ∈ { 'normal', 'muted', 'faint', 'faintest' }; background\n"
        "-- references a key in COLORS[mode] (currently only 'code_bg').\n"
        "M.TOKENS = {\n"
        + "\n".join(token_lines)
        + "\n}\n"
        "\n"
        "return M\n"
    )


def main() -> int:
    if not CANONICAL.exists():
        print(
            f"FAIL: canonical theme not found at {CANONICAL.relative_to(REPO_DIR)}.\n"
            f"      Did you forget `git submodule update --init`?",
            file=sys.stderr,
        )
        return 1

    canonical = json.loads(CANONICAL.read_text())
    expected = render(canonical)
    TARGET.parent.mkdir(parents=True, exist_ok=True)

    if "--check" in sys.argv:
        if not TARGET.exists():
            print(f"FAIL: {TARGET.relative_to(REPO_DIR)} missing", file=sys.stderr)
            return 1
        actual = TARGET.read_text()
        if actual != expected:
            print(
                f"FAIL: {TARGET.relative_to(REPO_DIR)} out of sync.\n"
                f"      Run: python3 scripts/gen-theme.py",
                file=sys.stderr,
            )
            return 1
        print(f"  ✓ {TARGET.relative_to(REPO_DIR)} matches generator")
        return 0

    TARGET.write_text(expected)
    print(f"wrote {TARGET.relative_to(REPO_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
